table dim_supplier
	lineageTag: 3819e2d1-55b2-4f60-b2b0-dd639ddb8977

	column supplier_id
		dataType: int64
		formatString: 0
		lineageTag: 8dd66b3b-13fb-4250-b55c-8be81b7b969f
		summarizeBy: none
		sourceColumn: supplier_id

	column supplier_name
		dataType: string
		lineageTag: d68a032f-94b6-4b37-917b-beb7c0f9a22c
		summarizeBy: none
		sourceColumn: supplier_name

	column region
		dataType: string
		lineageTag: ee464268-9def-47cb-9dd8-1e264d7cd9fd
		summarizeBy: none
		sourceColumn: region

	column country
		dataType: string
		lineageTag: 195df1d2-632f-521a-88eb-267d487a1c6a
		summarizeBy: none
		sourceColumn: country

	column sourcing_bloc
		dataType: string
		lineageTag: 029f3d17-eedc-50c0-baa7-76c8809d2b91
		summarizeBy: none
		sourceColumn: sourcing_bloc

	column supplier_tier
		dataType: string
		lineageTag: 33ac3424-5394-555f-82bb-c819ff9b355c
		summarizeBy: none
		sourceColumn: supplier_tier

	column is_qualified_alternate
		dataType: int64
		formatString: 0
		lineageTag: 29f2fb93-0a43-5f50-bb6e-21590773bdd4
		summarizeBy: none
		sourceColumn: is_qualified_alternate

	partition dim_supplier = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\dim_supplier.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"supplier_id", Int64.Type}, {"supplier_name", type text}, {"region", type text}, {"country", type text}, {"sourcing_bloc", type text}, {"supplier_tier", type text}, {"is_qualified_alternate", Int64.Type}})
				in
				    Typed

