table dim_date
	lineageTag: b1e198d8-4f8c-484f-842a-bcaf0b8a014e
	dataCategory: Time

	column full_date
		dataType: dateTime
		isUnique
		formatString: yyyy-mm-dd
		lineageTag: 4f1403cc-49fc-43fb-944a-612f27933f3f
		summarizeBy: none
		sourceColumn: full_date

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 6f81a049-664d-4dc3-960a-1c3d898d6071
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 60efb534-1acc-462b-8f3e-1f413b081ed7
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 342ece03-cb5d-4656-9cf5-812a972fe073
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 09a01bf4-2535-48ca-a456-7ab87c3a491e
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

	column week_of_year
		dataType: int64
		formatString: 0
		lineageTag: d99d19f7-c822-472c-8814-33b1956d5e9c
		summarizeBy: sum
		sourceColumn: week_of_year

		annotation SummarizationSetBy = Automatic

	column day_of_week_name
		dataType: string
		lineageTag: 781d19b1-f1fc-43ef-8754-0ee781529dda
		summarizeBy: none
		sourceColumn: day_of_week_name

	column year_month
		dataType: string
		lineageTag: 856fc0ed-b898-57a0-9921-ef1486e4ffc6
		summarizeBy: none
		sourceColumn: year_month
		sortByColumn: year_month_index

	column year_month_index
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8ce91609-0971-5158-88ad-6441c4c8ce4d
		summarizeBy: none
		sourceColumn: year_month_index

	partition dim_date = m
		mode: import
		source =
				let
				    StartDate = #date(2025, 1, 1),
				    EndDate = #date(2025, 6, 30),
				    Dates = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
				    AsTable = Table.FromList(Dates, Splitter.SplitByNothing(), {"full_date"}),
				    Typed = Table.TransformColumnTypes(AsTable, {{"full_date", type date}}),
				    AddYear = Table.AddColumn(Typed, "year", each Date.Year([full_date]), Int64.Type),
				    AddQuarter = Table.AddColumn(AddYear, "quarter", each Date.QuarterOfYear([full_date]), Int64.Type),
				    AddMonth = Table.AddColumn(AddQuarter, "month", each Date.Month([full_date]), Int64.Type),
				    AddMonthName = Table.AddColumn(AddMonth, "month_name", each Date.MonthName([full_date]), type text),
				    AddWeek = Table.AddColumn(AddMonthName, "week_of_year", each Date.WeekOfYear([full_date]), Int64.Type),
				    AddDayName = Table.AddColumn(AddWeek, "day_of_week_name", each Date.DayOfWeekName([full_date]), type text),
				    AddYearMonth = Table.AddColumn(AddDayName, "year_month",
				        each Date.ToText([full_date], "yyyy-MM"), type text),
				    AddYearMonthIndex = Table.AddColumn(AddYearMonth, "year_month_index",
				        each Date.Year([full_date]) * 12 + Date.Month([full_date]), Int64.Type)
				in
				    AddYearMonthIndex

